Add method to get all dashboards for a given user
salesforce/python-argusclient pull request #23
Opened 2020-10-26 23:32 UTC by j-ma-sf

Work item: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008IsYIIA0/view

2020-10-26 23:33 UTC, j-ma-sf commented
@haridsv

2020-10-28 11:58 UTC, hdara-sfdc requested changes

2020-10-28 11:58 UTC, hdara-sfdc commented on argusclient/client.py
> +        return self.argus._request("get", "dashboards", params=dict(ownerName=ownerName, shared=shared, limit=limit, version=version))
Shouldn't this be `owner`?
```suggestion
        return self.argus._request("get", "dashboards", params=dict(owner=ownerName, shared=shared, limit=limit, version=version))
```

2020-10-28 17:03 UTC, j-ma-sf commented on argusclient/client.py
> +        return self.argus._request("get", "dashboards", params=dict(ownerName=ownerName, shared=shared, limit=limit, version=version))
Oh, yes, good catch!

2020-10-28 17:06 UTC, j-ma-sf commented
@haridsv  Also updated the version

2020-10-28 17:18 UTC, hdara-sfdc approved these changes
lgtm

2020-10-28 17:18 UTC, merged

2020-10-28 17:33 UTC, j-ma-sf commented
@haridsv Thanks!