added formatting changes
salesforce/python-argusclient pull request #32
Opened 2021-07-28 10:41 UTC by snehabas

2021-07-28 10:42 UTC, snehabas commented
@hdara-sfdc Here are the formatting changes

2021-07-28 13:42 UTC, hdara-sfdc requested changes

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/client.py
> +            "data should be a list of %s objects" % self.obj_type)
```suggestion
        if not isinstance(data, list) or not isinstance(data[0], self.obj_type):
            raise TypeError("data should be a list of %s objects" % self.obj_type)
```

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/client.py
> -import collections
Why did the imports get split, some before copyright and some after?

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/client.py
> +            "Namespace id: %s doesn't match the id: %s that you are updating" % (namespace.id, id))
```suggestion
        if id != namespace.argus_id:
            raise ValueError("Namespace id: %s doesn't match the id: %s that you are updating" % (namespace.id, id))
```

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/client.py
> +            "Object id: %s doesn't match the id: %s that you are updating" % (obj.id, id))
```suggestion
        if id != obj.argus_id:
            raise ValueError("Object id: %s doesn't match the id: %s that you are updating" % (obj.id, id))
```

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/client.py
> +            "Need a composite Alert ID, got: %s" % type(comp_alert_id))
```suggestion
        if not isinstance(comp_alert_id, int):
            raise TypeError("Need a composite Alert ID, got: %s" % type(comp_alert_id))
```

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/client.py
> +            "Need a Notification object, got: %s" % type(notification))
```suggestion
        if not isinstance(notification, Notification):
            raise TypeError("Need a Notification object, got: %s" % type(notification))
```

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/client.py
> +        # self._request("get", "auth/logout")
This is actually undesirable. I avoid putting a space when commenting out code as it helps me visually distinguish that from real comments that are used as documentation.

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/model.py
> +        self.metric, ",".join("%s=%s" % (k, v) for k, v in self.tags.items())) or self.metric
This should be indented as it is a continuation of the previous statement.

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/model.py
> +            "argument should be of Trigger type, but is: %s" % type(value))
```suggestion
        if not isinstance(value, Trigger):
            raise ValueError( "argument should be of Trigger type, but is: %s" % type(value))
```

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/model.py
> +            "value should be of Notification type, but is: %s" % type(value))
```suggestion
        if not isinstance(value, Notification):
            raise ValueError("value should be of Notification type, but is: %s" % type(value))
```

2021-07-28 13:42 UTC, hdara-sfdc commented on argusclient/model.py
> +        Metric, Dashboard, AddListResult, User, Namespace, Annotation, Alert, Trigger, Notification, Permission):
This too is badly formatted, as it is a continuation of the previous line.

2021-08-28 07:59 UTC, hdara-sfdc commented on argusclient/model.py
> +        self.metric, ",".join("%s=%s" % (k, v) for k, v in self.tags.items())) or self.metric
```suggestion
        metricWithTags = tags and "%s{%s}" % (self.metric, ",".join("%s=%s" % (k, v) for k, v in self.tags.items())) \
                              or self.metric
```

2021-08-28 07:59 UTC, hdara-sfdc commented on argusclient/client.py
> +        # self._request("get", "auth/logout")
```suggestion
        #self._request("get", "auth/logout")
```

2021-08-28 07:59 UTC, hdara-sfdc commented on argusclient/model.py
> +        Metric, Dashboard, AddListResult, User, Namespace, Annotation, Alert, Trigger, Notification, Permission):
```suggestion
        for cls in (Metric, Dashboard, AddListResult, User, Namespace, Annotation,
                    Alert, Trigger, Notification, Permission):
```

2021-08-28 08:01 UTC, hdara-sfdc approved these changes
lgtm

2021-08-28 08:01 UTC, merged